#!/usr/bin/python3
#+
# Example use of Python’s ssl module: server-side.
# The code is written to avoid blocking on actual socket I/O, to make
# it easier to adapt to asynchronous usage.
#
# See the README for details on how to set things up to run this script.
#
# Copyright 2022 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0 <https://creativecommons.org/publicdomain/zero/1.0/>;
# do with it what you will.
#-

import sys
import enum
import socket
import select
import ssl
import getopt

class SOCK_NEED(enum.Enum) :
    "need to wait for socket to allow I/O of this type before TLS" \
    " communication can proceed."
    NOTHING = 0 # I/O can proceed
    READABLE = 1 # wait for socket to become readable
    WRITABLE = 2 # wait for socket to become writable
#end SOCK_NEED

class STATE(enum.Enum) :
    "the state of the connection protocol."
    NEED_HANDSHAKE = 0
    RECEIVE_REQUEST = 1
    SEND_RESPONSE = 2
    CLOSE = 3
#end STATE

listen_addr = "127.0.0.1"
listen_port = 6420
application_name = "x-incr-integer" # optionally negotiated between both ends
timeout = 5 # short value for easy testing
opts, args = getopt.getopt \
  (
    sys.argv[1:],
    "",
    []
  )
if len(args) not in (1, 3) :
    raise getopt.GetoptError("usage: %s «ca-cert-file» «server-cert-file» «server-key-file»" % sys.argv[0])
#end if
if len(args) == 3 :
    ca_cert_file, server_cert_file, server_key_file = args
else :
    ca_cert_file, = args
    server_cert_file = server_key_file = None
#end if

listen = socket.socket(family = socket.AF_INET, type = socket.SOCK_STREAM)
listen.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, True)
  # must be done before bind!
listen.bind((listen_addr, listen_port))
listen.setblocking(False)
listen.listen(1)
sctx = ssl.SSLContext(protocol = ssl.PROTOCOL_TLS_SERVER)
sctx.set_alpn_protocols([application_name])
sctx.verify_mode = ssl.VerifyMode.CERT_REQUIRED
sctx.check_hostname = False
if server_cert_file != None :
    sctx.load_cert_chain(server_cert_file, server_key_file)
#end if
sctx.load_verify_locations(ca_cert_file)
conn = None

while True :
    poll = select.poll()
    poll.register(listen, select.POLLIN)
    ready = poll.poll()
    assert len(ready) == 1
    ready, = ready
    assert ready[0] == listen.fileno()
    ready = ready[1]
    assert select.POLLIN & ready != 0
    try :
        conn = listen.accept()[0]
    except OSError as err :
        sys.stderr.write("connection accept error %s\n" % repr(err))
        conn = None
    #end try
    if conn == None :
        continue
    #end if
    conn.setblocking(False)
    sconn = sctx.wrap_socket(conn, server_side = True, do_handshake_on_connect = False)
    sock_need = SOCK_NEED.NOTHING
    state = STATE.NEED_HANDSHAKE
    while True :
        if sock_need != SOCK_NEED.NOTHING :
            sys.stderr.write("server need %s\n" % sock_need)
            poll = select.poll()
            poll.register \
              (
                sconn,
                {
                    SOCK_NEED.READABLE : select.POLLIN,
                    SOCK_NEED.WRITABLE : select.POLLOUT,
                }[sock_need]
              )
            ready = poll.poll(round(timeout * 1000))
            if len(ready) != 0 :
                assert len(ready) == 1
                ready, = ready
                assert ready[0] == sconn.fileno()
                if ready[1] & (select.POLLERR | select.POLLHUP | select.POLLRDHUP) != 0 :
                    sys.stderr.write("connection poll error %#0x\n" % ready[1])
                    state = None
                    break
                #end if
                assert ready[1] & (select.POLLIN | select.POLLOUT) != 0
                sock_need = SOCK_NEED.NOTHING
            else :
                sys.stderr.write("timeout after %.3fs\n" % timeout)
                state = STATE.CLOSE
            #end if
        #end if
        try :
            if state == STATE.NEED_HANDSHAKE :
                try :
                    sconn.do_handshake()
                    sys.stderr.write("handshake done, peer cert = %s\n" % sconn.getpeercert())
                    sys.stderr.write("shared_ciphers = %s, chosen cipher = %s\n" % (sconn.shared_ciphers(), sconn.cipher()))
                    sys.stderr.write("selected ALPN protocol = %s\n" % sconn.selected_alpn_protocol())
                    state = STATE.RECEIVE_REQUEST
                    req = b""
                except ssl.SSLError as fail :
                    if isinstance(fail, (ssl.SSLWantReadError, ssl.SSLWantWriteError)) :
                        raise # pass to common handler
                    #end if
                    sys.stderr.write("handshake failed: %s\n" % str(fail))
                    state = STATE.CLOSE
                #end try
            elif state == STATE.RECEIVE_REQUEST :
                data = sconn.recv(128)
                sys.stderr.write("data received = %s\n" % repr(data))
                if len(data) != 0 :
                    if len(req) + len(data) > 255 :
                        # prevent clients making me use too much memory
                        sys.stderr.write("too much data received: %d + %d bytes\n" % (len(req), len(data)))
                        state = STATE.CLOSE
                        break
                    #end if
                    req += data
                    reqend = req.find(b"\n")
                    if reqend >= 0 :
                        data = req[reqend + 1:]
                        if len(data) != 0 :
                            sys.stderr.write("leftover data after req: %s\n" % repr(data))
                        #end if
                        req = req[:reqend]
                        try :
                            val = int(req.decode())
                        except (UnicodeDecodeError, ValueError) :
                            val = None
                        #end try
                        if val != None :
                            data = (str(val + 1) + "\n").encode()
                            state = STATE.SEND_RESPONSE
                        else :
                            sys.stderr.write("bad value received\n")
                            state = STATE.CLOSE
                        #end if
                    #end if
                else :
                    state = STATE.CLOSE
                #end if
            elif state == STATE.SEND_RESPONSE :
                sconn.sendall(data)
                state = STATE.RECEIVE_REQUEST
                req = b""
            elif state == STATE.CLOSE :
                try :
                    sconn.shutdown(socket.SHUT_RDWR)
                    sconn.close()
                except OSError as err :
                    sys.stderr.write("socket shutdown error %s\n" % repr(err))
                #end try
                state = None
                break
            #end if
            sys.stderr.write("state is now %s\n" % repr(state))
        except ssl.SSLWantReadError :
            sock_need = SOCK_NEED.READABLE
        except ssl.SSLWantWriteError :
            sock_need = SOCK_NEED.WRITABLE
        except ssl.SSLError as err :
            sys.stderr.write("Unexpected SSL error %s\n" % repr(err))
            if state != STATE.CLOSE :
                state = STATE.CLOSE
            else :
                state = None
                break
            #end if
        #end try
    #end while
#end while
